// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpDWIzGc27_0y9pm9YgqePfm37yfLPl1Y',
    appId: '1:36227163986:web:b828637a9752e8af8d7c8b',
    messagingSenderId: '36227163986',
    projectId: 'mobileappdevelopment-9a8c1',
    authDomain: 'mobileappdevelopment-9a8c1.firebaseapp.com',
    storageBucket: 'mobileappdevelopment-9a8c1.firebasestorage.app',
    measurementId: 'G-JQNVHMWC43',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtqby2g4pGDAgtF7Ydx-iL_d-ZpWm1C54',
    appId: '1:36227163986:android:fa1e505aa0606d2a8d7c8b',
    messagingSenderId: '36227163986',
    projectId: 'mobileappdevelopment-9a8c1',
    storageBucket: 'mobileappdevelopment-9a8c1.firebasestorage.app',
  );
}
