// Autogenerated from Pigeon (v1.0.19), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name
// @dart = 2.12
import 'dart:async';
import 'dart:typed_data' show Uint8List, Int32List, Int64List, Float64List;

import 'package:flutter/foundation.dart' show WriteBuffer, ReadBuffer;
import 'package:flutter/services.dart';

class PigeonUserDetails {
  String? name;
  int? age;

  PigeonUserDetails({this.name, this.age});

  Object encode() {
    final Map<Object?, Object?> pigeonMap = <Object?, Object?>{};
    pigeonMap['name'] = name;
    pigeonMap['age'] = age;
    return pigeonMap;
  }

  static PigeonUserDetails decode(Object message) {
    final Map<Object?, Object?> pigeonMap = message as Map<Object?, Object?>;
    return PigeonUserDetails(
      name: pigeonMap['name'] as String?,
      age: pigeonMap['age'] as int?,
    );
  }
}

class _PigeonApiCodec extends StandardMessageCodec {
  const _PigeonApiCodec();

  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is PigeonUserDetails) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128:
        return PigeonUserDetails.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class PigeonApi {
  /// [PigeonApi]의 생성자입니다. [binaryMessenger] 매개변수는 의존성 주입에 사용됩니다.
  /// 만약 null이면, 기본 BinaryMessenger가 사용되어 호스트 플랫폼과 통신합니다.
  PigeonApi({BinaryMessenger? binaryMessenger}) : _binaryMessenger = binaryMessenger;

  final BinaryMessenger? _binaryMessenger;

  static const MessageCodec<Object?> codec = _PigeonApiCodec();

  Future<PigeonUserDetails?> getUserDetails(String arg_uid) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
      'dev.flutter.pigeon.PigeonApi.getUserDetails',
      codec,
      binaryMessenger: _binaryMessenger,
    );
    final Map<Object?, Object?>? replyMap =
    await channel.send(<Object>[arg_uid]) as Map<Object?, Object?>?;
    if (replyMap == null) {
      throw PlatformException(
        code: 'channel-error',
        message: '채널에서 연결을 설정할 수 없습니다.',
      );
    } else if (replyMap['error'] != null) {
      final Map<Object?, Object?> error = replyMap['error'] as Map<Object?, Object?>;
      throw PlatformException(
        code: error['code'] as String? ?? 'unknown',
        message: error['message'] as String?,
        details: error['details'],
      );
    } else {
      return replyMap['result'] as PigeonUserDetails?;
    }
  }
}
